#!/bin/bash

echo "🚀 Medical Insights App Deployment Helper"
echo "=========================================="
echo ""

echo "📋 Prerequisites Check:"
echo "1. Ensure all code is committed and pushed to GitHub"
echo "2. Have Render account ready (free tier)"
echo "3. Have Vercel account ready (free tier)"
echo ""

echo "🔧 Step 1: Deploy Backend to Render"
echo "   - Go to: https://render.com"
echo "   - Create new Web Service"
echo "   - Connect your GitHub repo"
echo "   - Use these settings:"
echo "     * Name: medical-insights-backend"
echo "     * Environment: Python 3"
echo "     * Build Command: cd backend && pip install -r requirements.txt"
echo "     * Start Command: cd backend && uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo "     * Plan: Free"
echo ""

echo "🌐 Step 2: Deploy Frontend to Vercel"
echo "   - Go to: https://vercel.com"
echo "   - Create new project"
echo "   - Import your GitHub repo"
echo "   - Use these settings:"
echo "     * Framework: Vite"
echo "     * Root Directory: frontend"
echo "     * Build Command: npm run build"
echo "     * Output Directory: dist"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "   - In Vercel, add environment variable:"
echo "     * Name: VITE_API_URL"
echo "     * Value: https://your-backend-name.onrender.com"
echo ""

echo "✅ Step 4: Test Your Deployment"
echo "   - Backend health: https://your-backend-name.onrender.com/health"
echo "   - Frontend: https://your-project-name.vercel.app"
echo ""

echo "📖 For detailed instructions, see: DEPLOYMENT_GUIDE.md"
echo ""
echo "🎉 Your app will be live worldwide once deployed!"
